version: '3.3'

services:
  diffusecord:
    container_name: diffusecord 
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/diffusecord

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
